CGIT_SCRIPT_NAME = cgit.cgi
# a directory that can be served
CGIT_SCRIPT_PATH = /home/oils/www/mb.oils.pub/cgit
CGIT_DATA_PATH = $(CGIT_SCRIPT_PATH)
CGIT_CONFIG = /home/oils/cgit/cgitrc
CACHE_ROOT = /home/oils/cgit/cache
prefix = /home/oils/cgit
