CGIT_SCRIPT_NAME = cgit.cgi
# the cgit.cgi binary is put under a directory that can be served
CGIT_SCRIPT_PATH = /home/oils/www/d.oils.pub/cgit
# configuration is versioned
CGIT_CONFIG = /home/oils/git/oils-for-unix/cgit/mb-cgitrc
CACHE_ROOT = /home/oils/cgit/cache
prefix = /home/oils/cgit
